spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/springsecurity
    driver-class-name: org.h2.Driver
    username: sa
    password: 11

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true